- type: job
  id: Miner
  name: job-name-miner
  description: job-description-miner
  playTimeTracker: JobMiner
  icon: "JobIconShaftMiner"
  startingGear: MinerGear
  supervisors: job-supervisors-qm
  access:
    - Cargo
    - Salvage
    - Maintenance
    - External

- type: startingGear
  id: MinerGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCampones2
    #back: ClothingBackpackMusicianFilled
    #eyes: ClothingEyesGlassesSunglasses
    shoes: ClothingShoesBootsLaceup
    #id: MusicianPDA
    #ears: ClothingHeadsetService
    #outerClothing: ClothingOuterApronChef
    #belt: ClothingBeltChefFilled
  #satchel: ClothingBackpackSatchelMusicianFilled
  #duffelbag: ClothingBackpackDuffelMusicianFilled
