- type: job
  id: Wizard
  name: job-name-wizard
  description: job-description-wizard
  playTimeTracker: JobWizard
  startingGear: ScientistGear
  icon: "JobIconScientist"
  supervisors: job-supervisors-rd
  access:
    - Research
    - Maintenance

- type: startingGear
  id: ScientistGear
  equipment:
    ears: ClothingHeadsetScience
  #storage:
  #back:
  #- Stuff

- type: chameleonOutfit
  id: ScientistChameleonOutfit
  job: Scientist
  equipment:
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckTieSci
    outerClothing: ClothingOuterCoatRnd
    gloves: ClothingHandsGlovesLatex
