- type: job
  id: Nun
  name: job-name-nun
  description: job-description-nun
  playTimeTracker: JobNun
  startingGear: ChaplainGear
  icon: "JobIconChaplain"
  supervisors: job-supervisors-rd
  access:
    - Chapel
    - Research
    - Maintenance

- type: startingGear
  id: ChaplainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChaplain
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
    id: ChaplainPDA
    ears: ClothingHeadsetScience
    pocket1: BookPsionicsGuidebook
  innerClothingSkirt: ClothingUniformJumpskirtChaplain
  satchel: ClothingBackpackSatchelChaplainFilled
  duffelbag: ClothingBackpackDuffelChaplainFilled
