- type: department
  id: Royalty
  name: department-Royalty
  description: department-royalty-description
  color: "#701442"
  weight: 200
  roles:
    - Baron
    - Baroness
    - Bishop
    - LordCommanderOfTheGuard
    - Hand

- type: department
  id: Kingsguard
  name: department-Kingsguard
  description: department-kingsguard-description
  color: "#701442"
  weight: 199
  roles:
    - LordCommanderOfTheGuard
    - Guard
    - Knight
    - WardenMD

- type: department
  id: Clergy
  name: department-Clergy
  description: department-clergy-description
  color: "#701442"
  weight: 198
  roles:
    - Bishop
    - Chaplain
    - Nun
    - Inquisitor
    - Alchemist

- type: department
  id: Market
  name: department-Market
  description: department-market-description
  color: "#701442"
  weight: 197
  roles:
    - Treasurer
    - Miner
    - Carrier

- type: department
  id: Civil
  name: department-Civil
  description: department-civil-description
  color: "#701442"
  weight: 197
  roles:
    - Executioner
    - ChefMD
    - Jester
    - Tavernkeeper
    - Bard
    - Maid
