- type: job
  id: Alchemist
  name: job-name-alchemist
  description: job-description-alchemist
  playTimeTracker: JobAlchemist
  startingGear: ChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-cmo
  access:
    - Medical
    - Chemistry
    - Maintenance

- type: startingGear
  id: ChemistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChemistry
    back: ClothingBackpackChemistryFilled
    shoes: ClothingShoesColorWhite
    id: ChemistryPDA
    ears: ClothingHeadsetMedical
  innerClothingSkirt: ClothingUniformJumpskirtChemistry
  satchel: ClothingBackpackSatchelChemistryFilled
  duffelbag: ClothingBackpackDuffelChemistryFilled
