- type: job
  id: MasterWizard
  name: job-name-md
  description: job-description-md
  playTimeTracker: JobMD
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
    - Research
    - Command
    - Maintenance
    - ResearchDirector
    - Brig
    - Cryogenics
  special:
    - !type:AddImplantSpecial
      implants: [MindShieldImplant]
    - !type:AddComponentSpecial
      components:
        - type: CommandStaff
