- type: job
  id: Nun
  name: job-name-nun
  description: job-description-nun
  playTimeTracker: JobNun
  startingGear: NunGear
  icon: "JobIconChaplain"
  supervisors: job-supervisors-rd
  access:
    - Chapel
    - Research
    - Maintenance

- type: startingGear
  id: NunGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCampones2
    #back: ClothingBackpackMusicianFilled
    #eyes: ClothingEyesGlassesSunglasses
    shoes: ClothingShoesBootsLaceup
    #id: MusicianPDA
    #ears: ClothingHeadsetService
    #outerClothing: ClothingOuterApronChef
    #belt: ClothingBeltChefFilled
  #satchel: ClothingBackpackSatchelMusicianFilled
  #duffelbag: ClothingBackpackDuffelMusicianFilled
