- type: job
  id: Peasant
  name: job-name-peasant
  description: job-description-peasant
  playTimeTracker: JobPeasant
  startingGear: JanitorMaidGear
  icon: "JobIconJanitor"
  supervisors: job-supervisors-hop
  access:
    - Service
    - Janitor
    - Maintenance
