- type: job
  id: ChefMD
  name: job-name-chef
  description: job-description-chef
  playTimeTracker: JobChefMD
  startingGear: ChefGear
  icon: "JobIconChef"
  supervisors: job-supervisors-hop
  access:
    - Service
    - Maintenance
    - Kitchen
  extendedAccess:
    - Hydroponics
    - Bar #Nyano - Summary: After this line, Professional Che is a component to be added. Very important.

- type: startingGear
  id: ChefGear
  subGear:
    - ChefPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChef
    head: ClothingHeadHatChef
    back: ClothingBackpackFilled
    mask: ClothingMaskItalianMoustache
    shoes: ClothingShoesColorBlack
    id: ChefPDA
    ears: ClothingHeadsetService
    outerClothing: ClothingOuterApronChef
    belt: ClothingBeltChefFilled
  innerClothingSkirt: ClothingUniformJumpskirtChef
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
