- type: job
  id: ChefMD
  name: job-name-chef
  description: job-description-chef
  playTimeTracker: JobChefMD
  startingGear: ChefMDGear
  icon: "JobIconChef"
  supervisors: job-supervisors-hop
  access:
    - Service
    - Maintenance
    - Kitchen
  extendedAccess:
    - Hydroponics
    - Bar #Nyano - Summary: After this line, Professional Che is a component to be added. Very important.

- type: startingGear
  id: ChefMDGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCampones2
    #back: ClothingBackpackMusicianFilled
    #eyes: ClothingEyesGlassesSunglasses
    shoes: ClothingShoesBootsLaceup
    #id: MusicianPDA
    #ears: ClothingHeadsetService
    #outerClothing: ClothingOuterApronChef
    #belt: ClothingBeltChefFilled
  #satchel: ClothingBackpackSatchelMusicianFilled
  #duffelbag: ClothingBackpackDuffelMusicianFilled
