- type: department
  id: Council
  name: department-Council
  description: department-council-description
  color: "#701442"
  weight: 200
  roles:
    - King
    - Queen
    - Bishop
    - LordCommanderOfTheGuard
    - Hand
    - Treasurer

- type: department
  id: Kingsguard
  name: department-Kingsguard
  description: department-kingsguard-description
  color: "#701442"
  weight: 199
  roles:
    - LordCommanderOfTheGuard
    - Guard
    - Knight
    - WardenMD

- type: department
  id: Clergy
  name: department-Clergy
  description: department-clergy-description
  color: "#701442"
  weight: 198
  roles:
    - Bishop
    - Chaplain
    - Nun
    - Inquisitor

- type: department
  id: Magic Tower
  name: department-Magic-Tower
  description: department-magic-tower-description
  color: "#701442"
  weight: 197
  roles:
    - Alchemist
    - MasterWizard
    - Wizard

- type: department
  id: Market
  name: department-Market
  description: department-market-description
  color: "#701442"
  weight: 196
  roles:
    - Treasurer
    - Miner
    - Carrier

- type: department
  id: Civil
  name: department-Civil
  description: department-civil-description
  color: "#701442"
  weight: 195
  roles:
    - Executioner
    - ChefMD
    - Jester
    - Tavernkeeper
    - Bard
    - Maid
    - Peasant
