- type: job
  id: Baron
  name: job-name-baron
  description: job-description-baron
  playTimeTracker: JobKing
  weight: 20
  startingGear: CaptainGear
  icon: JobIconCaptain
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
    - AllAccess
  special:
    - !type:AddImplantSpecial
      implants: [MindShieldImplant]
    - !type:AddComponentSpecial
      components:
        - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptain
    shoes: ClothingShoesBootsLaceup
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  innerClothingSkirt: ClothingUniformJumpskirtCaptain
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled
